### ISSUE TITLE
No module named 'pretrainedmodels'

### ISSUE THREAD

**Issue by deepalchemist** [Confusezius/metric-learning-mining-interclass-characteristics#2]
File "/code root/datasets.py", line 30, in <module>
    import pretrainedmodels.utils as utils
ModuleNotFoundError: No module named 'pretrainedmodels'

**Comment by Confusezius** [comment]
Hey there! `pretrainedmodels` is a library that needs to be installed via `pip install pretrainedmodels` :).

**Comment by deepalchemist** [comment]
It works.
