### ISSUE TITLE
Encoder beta

### ISSUE THREAD

**Issue by jlian2** [Confusezius/metric-learning-mining-interclass-characteristics#5]
I am kind of confused about Encoder beta. If my understanding is correct, you just set number of classes in surrogate task as hyperparameter. But what is the purpose of classifying samples in surrogate. If my understanding is correct. you have a car1-left and car1-right, they are all car1. Our goal is to distinguish between car1 and car2, why are you distinguishing car1-left and car1-right?

**Comment by Confusezius** [comment]
The surrogate task classifies not the training samples directly. Instead, assuming that class distribution can sufficiently be approximated by a gaussian, subtracts the mean and then performs clustering. This allows the model to also recover intraclass properties. The idea is to find explicit representations for such features that the main embedding can leverage for better performance.
