### ISSUE TITLE
Code of "Sharing Matters for Generalization in Deep Metric Learning, IEEE 2020"

### ISSUE THREAD

**Issue by Sunjuhyeong** [Confusezius/metric-learning-mining-interclass-characteristics#8]
Hi! 
I'm interested in your work.

By any chance, would you like to publish the code of the Sharing Matters for Generalization in Deep Metric Learning, IEEE 2020 paper?
(Sorry for asking a question unrelated to the Github repo.)

Sincerely,
Juhyeong Seon

**Comment by Confusezius** [comment]
Hi Juhyeong!

No worries about asking it here :). Regarding the code, feel free to just look here: https://github.com/Confusezius/ECCV2020_DiVA_MultiFeature_DML

It contains the code for the follow-up submitted to ECCV that looks into additionally mineable tasks, but also includes the class-sharing task suggested in our IEEE paper! Let me know if there is anything else I can help you with!

**Comment by Sunjuhyeong** [comment]
Aha, Thank you for kind reply !
